apiVersion: v2
name: dummy-rsc
type: application
version: 0.0.1
appVersion: 11.7.0
description: external resources needed for dummy service
dependencies:
  - name: postgresql
    version: 8.6.4
    repository: https://charts.helm.sh/stable
